### ISSUE TITLE
Multiple iframes with different sizes

### ISSUE THREAD

**Issue by donaldallen** [edenspiekermann/iframify#11]
I have an element collage that I'd like to showcase each component in multiple sizes: desktop, tablet, mobile. Is that possible with iframify? Right now I have it working for mobile, as I have iframe set to 320px in CSS. But how would I create another one at medium viewport? I can't seem to set a class on the generated iframe.

**Comment by KittyGiraudel** [comment]
How about something like:

``` html
<div class="showcase--small">
  <div class="iframify">
    <div class="component">…</div>
  </div>
</div>

<div class="showcase--medium">
  <div class="iframify">
    <div class="component">…</div>
  </div>
</div>

<div class="showcase--large">
  <div class="iframify">
    <div class="component">…</div>
  </div>
</div>
```

``` css
.showcase--small > iframe {
  width: 320px;
}

.showcase--medium > iframe {
  width: 720px;
}

.showcase--large > iframe {
  width: 1280px;
}
```

``` js
var components = document.querySelectorAll('.iframify > :first-child');
var iframes = Array.prototype.map.call(components, iframify);
```
